Readme update
djolewalker/zmijica pull request #2
Opened 2021-12-09 14:51 UTC by djolewalker

2021-12-24 10:42 UTC, DejanBesic requested changes
Change this!

2021-12-24 10:43 UTC, djolewalker reviewed
Done

2021-12-24 10:46 UTC, DejanBesic approved these changes

2021-12-24 11:03 UTC, djolewalker commented on README.md
> +
Remove this line

2021-12-24 14:11 UTC, djolewalker reviewed
sss

2021-12-24 14:11 UTC, djolewalker commented on README.md
> +
simpleee

2022-01-13 13:50 UTC, djolewalker commented on README.md
> +
asdad

2022-01-29 18:08 UTC, closed without merging